// Tourist Dungeon — TD_VAULTLIB: the authored vault corpus, embedded for the browser.
// GENERATED by scripts/build_vaultlib.py from tests/fixtures/vaults/*.des (the authoring
// source of truth). DO NOT hand-edit; edit the .des files and re-run the builder.
// The assembler parses these via TD_VAULTFMT.parse and stamps them as rooms.
"use strict";

var TD_VAULTLIB = (function () {
  var SOURCES = [
  // landmark-hall.des
  `NAME: ws_landmark_hall
TAGS: worked_stone room large landmark
WEIGHT: 3
EDGES: N door, S door, W door, E door
SUBST: ? = . . o
MAP
#####+#####
#.o.....o.#
#.........#
+....?....#
#.........#
#....?....+
#.o.....o.#
#####+#####
ENDMAP`,
  // large-hall.des
  `NAME: ws_large_hall
TAGS: worked_stone room large
WEIGHT: 5
EDGES: N door, S door, W door, E door
SUBST: ? = . . o
MAP
#####+#####
#.o.....o.#
#....G....#
+...?.?...+
#....G....#
#.o.....o.#
#####+#####
ENDMAP`,
  // large-irregular.des
  `NAME: ws_large_irregular
TAGS: worked_stone room large
WEIGHT: 4
EDGES: N door, E door, S door
SUBST: , = . #
MAP
###+#####
#,.....,#
#.......#
#.....$.+
#.......#
#,.....,#
###+#####
ENDMAP`,
  // loot-vault.des
  `NAME: ws_loot_vault
TAGS: worked_stone room vault
WEIGHT: 4
EDGES: N door, S door
SUBST: ? = . o
MAP
###+###
#o...o#
#.$.$.#
#.?.?.#
#o...o#
###+###
ENDMAP`,
  // medium-hall.des
  `NAME: ws_medium_hall
TAGS: worked_stone room medium
WEIGHT: 8
EDGES: N door, S door, W door, E door
SUBST: ? = . o
MAP
####+####
#.o...o.#
#.?...?.#
+.......+
#.?...?.#
#.o...o.#
####+####
ENDMAP`,
  // medium-pillared.des
  `NAME: ws_medium_pillared
TAGS: worked_stone room medium
WEIGHT: 7
EDGES: W door, E door
MAP
#########
#.o.o.o.#
+...$...+
#.o.o.o.#
#########
ENDMAP`,
  // notice-room.des
  `NAME: ws_notice_room
TAGS: worked_stone room notice
WEIGHT: 6
EDGES: W door
MAP
#######
#..G..#
+.....#
#..o..#
#######
ENDMAP`,
  // secret-cache.des
  `NAME: secret_cache
TAGS: room secret
WEIGHT: 4
MAP
#####
#?.?#
#.$.#
##+##
ENDMAP`,
  // small-rect.des
  `NAME: ws_small_rect
TAGS: worked_stone room small
WEIGHT: 10
EDGES: W door, E door
MAP
#######
#.....#
+..$..+
#.....#
#######
ENDMAP`,
  // small-square.des
  `NAME: ws_small_square
TAGS: worked_stone room small
WEIGHT: 10
EDGES: N door, S door
MAP
##+##
#...#
#...#
#...#
##+##
ENDMAP`,
  // stair-hall.des
  `NAME: stair_hall
TAGS: room stair landmark
WEIGHT: 5
EDGES: N door
MAP
##+##
#.G.#
#...#
#.{.#
#####
ENDMAP`,
  // tiny-closet.des
  `NAME: ws_tiny_closet
TAGS: worked_stone room tiny secret
WEIGHT: 6
EDGES: S door
MAP
#####
#?$?#
#...#
##+##
ENDMAP`,
  // worked-room.des
  `; authored-for-test (not real DCSS — no network to fetch GPL); DCSS-shaped to prove the format
NAME: worked_room
TAGS: worked_stone room
WEIGHT: 10
EDGES: N door, S door, W door, E door
SUBST: ? = . o
MAP
####+####
#.o...o.#
+...$...+
#.?...?.#
#.o...o.#
####+####
ENDMAP`
  ];
  var _parsed = null;
  function all() { if (!_parsed) _parsed = SOURCES.map(function (s) { return TD_VAULTFMT.parse(s); }); return _parsed; }
  return { all: all, SOURCES: SOURCES, count: SOURCES.length };
})();

if (typeof module !== "undefined" && module.exports) { module.exports = TD_VAULTLIB; }
